"""aping-common: 5 个 aping-* skill 共享的工具库"""
from .aping_common import (
    PROJECT_ROOT,
    DEFAULT_OUTPUT_DIR,
    WINDOWS_CJK_FONTS,
    setup_console,
    log,
    get_ffmpeg,
    get_ffprobe,
    get_cjk_font,
    seconds_to_srt_time,
    srt_time_to_seconds,
    parse_srt,
    write_srt,
    run_ffmpeg,
    get_video_info,
    get_duration,
    get_resolution,
    ensure_dir,
    probe_duration,
    safe_filename,
)

__all__ = [
    "PROJECT_ROOT",
    "DEFAULT_OUTPUT_DIR",
    "WINDOWS_CJK_FONTS",
    "setup_console",
    "log",
    "get_ffmpeg",
    "get_ffprobe",
    "get_cjk_font",
    "seconds_to_srt_time",
    "srt_time_to_seconds",
    "parse_srt",
    "write_srt",
    "run_ffmpeg",
    "get_video_info",
    "get_duration",
    "get_resolution",
    "ensure_dir",
    "probe_duration",
    "safe_filename",
]
